### ISSUE TITLE
the `format=json` parameter needs to be omitted from `getToken` API calls 

### ISSUE THREAD

**Issue by kquinsland** [michaelday/rtm-js#10]
See here:

https://groups.google.com/d/msg/rememberthemilk-api/uW0IGLXEiIg/ss8MPnjFBAAJ

Basically, a URL that looks like this:

https://api.rememberthemilk.com/services/rest/?frob=$FROB&method=rtm.auth.getToken&format=json&api_key=283fdb6a7f672e30f2d1cc210bb24990&api_sig=$HASH

needs to look like this:
https://api.rememberthemilk.com/services/rest/?frob=$FROB&method=rtm.auth.getToken&api_key=283fdb6a7f672e30f2d1cc210bb24990&api_sig=$NEW_HASH.

Just a FYI for anybody else that uses this library in a project and wonders why you're getting the dreaded `Uh oh... something went wrong.` message

You can see that the API docs do not specify a format for `getToken` calls:
https://www.rememberthemilk.com/services/api/methods/rtm.auth.getToken.rtm

**Comment by jondcoleman** [comment]
Thanks for opening this issue!

**Comment by michaelday** [comment]
I'm sorry I haven't had time to get to this issue, but in the meantime, PRs are welcome.

**Comment by WL-Amigo** [comment]
I made modification to address this issue. Could you check my PR?
Thanks in advance!

**Comment by aranel616** [comment]
Closed in #11. Thanks @WL-Amigo for the contribution!
