### ISSUE TITLE
Create an npmjs.org package? :)

### ISSUE THREAD

**Issue by vergenzt** [michaelday/rtm-js#7]

**Comment by vergenzt** [comment]
Any update on this?

**Comment by michaelday** [comment]
I have an update on this!

https://www.npmjs.com/package/rtm-js

You can now grab rtm-js for your node project like so:

`npm install --save-dev rtm.js`

And use it like normal:

```javascript
var RememberTheMilk = require('rtm-js');
var rtm = new RememberTheMlik(...);
```

**Comment by vergenzt** [comment]
Thanks! :+1:
