### ISSUE TITLE
Login failed / Invalid auth token

### ISSUE THREAD

**Issue by GeoffreyPlitt** [michaelday/rtm-js#9]
I've got the correct API key and secret configured, but I'm getting the following with any API calls:
```javascript
{ rsp: 
   { stat: 'fail',
     err: { code: '98', msg: 'Login failed / Invalid auth token' } } }
```

Then I read https://www.rememberthemilk.com/services/api/authentication.rtm, and looking back at your code, I don't see any reference to auth or tokens. Seems like I need to do something with auth tokens to make this work.

Please advise, thanks.

**Comment by michaelday** [comment]
You can authenticate by using the following code:

```javascript
rtm.get('rtm.auth.getFrob', function(resp){
    frob = resp.rsp.frob;
    var authUrl = rtm.getAuthUrl(frob);
});
```

If you visit the auth url in your browser, you can authorize your application. After that, you can use the following code to get the auth token:

```javascript
rtm.get('rtm.auth.getToken', {frob: frob}, function(resp){
    rtm.auth_token = resp.rsp.auth.token;
});
```

Once `rtm.auth_token` is set, it will be used for any future requests that use `rtm.get`.

```javascript
rtm.get('rtm.lists.getList', function(resp){
    // ...
});
```

You can see the full working example for for [node](https://github.com/michaelday/rtm-js/blob/master/examples/node/example.js) or [web](https://github.com/michaelday/rtm-js/blob/master/examples/web/example.html) to get a better idea of how that all works together in practice.

I hope that helps. If that doesn't work, create a gist with your code in it and reopen this ticket. I'll take a look and try to help you out.

**Comment by GeoffreyPlitt** [comment]
Great, thanks!
